export const BRAND_NAME = 'Swan Mattresses';
export const TAGLINE_MAIN = 'Experience Absolute Nirvana';
export const TAGLINE_SUB = 'In Every Night’s Sleep';
export const WEBSITE_URL = 'https://swanmattresses.com';
export const CONTACT_PHONE = '+918317668162';
export const SOCIAL_INSTAGRAM = 'https://www.instagram.com/swanmattresses/';
export const SOCIAL_FACEBOOK = 'https://www.facebook.com/profile.php?id=61570115621869';
export const WHATSAPP_LINK = 'https://wa.me/918317668162';
export const STORE_LOCATION = 'Rampally, Telangana, India';
export const STORE_LOCATION_URL = 'https://maps.google.com/?q=Rampally,+Telangana,+India';
