
export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  imageId: string;
  href: string;
  category: 'Mattresses' | 'Beds' | 'Sofas';
  material?: string;
  size?: string;
  description: string;
  features: string[];
}

export const allProducts: Product[] = [
  // Mattresses
  { 
    id: '1', 
    slug: 'cloudcomfort-premium',
    name: 'CloudComfort Premium', 
    price: 25999, 
    oldPrice: 32999, 
    rating: 4.8, 
    reviews: 120, 
    imageId: 'product-mattress-1', 
    href: '/product/cloudcomfort-premium', 
    category: 'Mattresses', 
    material: 'Foam', 
    size: 'Queen',
    description: 'Experience the ultimate in comfort with the CloudComfort Premium mattress. Featuring our latest sleep technology, this mattress provides a cloud-like feel with the support your body needs. Wake up refreshed and ready to take on the day.',
    features: [
      'Advanced multi-layer foam construction',
      'Cooling gel-infused top layer',
      'Hypoallergenic materials',
      '10-year warranty',
    ],
  },
  { 
    id: '2', 
    slug: 'orthodream-support',
    name: 'OrthoDream Support', 
    price: 18999, 
    rating: 4.9, 
    reviews: 250, 
    imageId: 'product-mattress-2', 
    href: '/product/orthodream-support', 
    category: 'Mattresses', 
    material: 'Spring', 
    size: 'King',
    description: 'Designed for optimal spinal alignment, the OrthoDream Support mattress provides firm, targeted support to relieve pressure points and reduce back pain. Its robust spring system ensures durability and long-lasting comfort.',
    features: [
      'Reinforced orthopedic spring system',
      'High-density support foam',
      'Breathable fabric cover',
      'Recommended by chiropractors',
    ],
  },
  { 
    id: '3', 
    slug: 'luxesleep-gel-memory',
    name: 'LuxeSleep Gel Memory', 
    price: 29999, 
    oldPrice: 38999, 
    rating: 4.7, 
    reviews: 98, 
    imageId: 'product-mattress-3', 
    href: '/product/luxesleep-gel-memory', 
    category: 'Mattresses', 
    material: 'Hybrid', 
    size: 'Queen',
    description: 'Indulge in the luxurious feel of our LuxeSleep mattress. Combining cooling gel memory foam with a supportive coil base, it contours to your body for personalized comfort while ensuring you stay cool all night long.',
    features: [
      'Gel-infused memory foam for cooling',
      'Individually wrapped pocket coils',
      'Plush pillow-top for added luxury',
      'Minimal motion transfer',
    ],
  },
  { 
    id: '4', 
    slug: 'ecorest-organic-latex',
    name: 'EcoRest Organic Latex', 
    price: 34999, 
    rating: 4.9, 
    reviews: 75, 
    imageId: 'product-mattress-4', 
    href: '/product/ecorest-organic-latex', 
    category: 'Mattresses', 
    material: 'Latex', 
    size: 'Single',
    description: 'Embrace natural comfort with the EcoRest mattress. Made from 100% organic latex, it offers a responsive, buoyant feel that is both supportive and eco-friendly. Naturally hypoallergenic and durable.',
    features: [
      '100% GOLS certified organic latex',
      'Naturally breathable and cooling',
      'Resistant to dust mites and mold',
      'Sustainably sourced materials',
    ],
  },
  // Beds
  { 
    id: '5', 
    slug: 'majestic-wooden-frame',
    name: 'Majestic Wooden Frame', 
    price: 45999, 
    rating: 4.8, 
    reviews: 80, 
    imageId: 'product-bed-1', 
    href: '/product/majestic-wooden-frame', 
    category: 'Beds', 
    material: 'Solid Wood', 
    size: 'King',
    description: 'The Majestic Wooden Frame is a statement of timeless elegance. Crafted from solid Sheesham wood, its robust construction and rich finish bring a touch of regal charm to any bedroom.',
    features: [
      'Made from premium solid Sheesham wood',
      'Classic high-headboard design',
      'Durable and long-lasting construction',
      'Easy to assemble',
    ],
  },
  { 
    id: '6', 
    slug: 'plush-upholstered-bed',
    name: 'Plush Upholstered Bed', 
    price: 52999, 
    oldPrice: 60000, 
    rating: 4.9, 
    reviews: 110, 
    imageId: 'product-bed-2', 
    href: '/product/plush-upholstered-bed', 
    category: 'Beds', 
    material: 'Fabric', 
    size: 'Queen',
    description: 'Sink into sophistication with the Plush Upholstered Bed. Its soft, tufted headboard and premium fabric finish create a cozy and inviting centerpiece for your bedroom retreat.',
    features: [
      'Elegant button-tufted headboard',
      'Upholstered in premium, soft fabric',
      'Sturdy wooden slat support system',
      'Available in multiple color options',
    ],
  },
  { 
    id: '7', 
    slug: 'smart-storage-bed',
    name: 'Smart Storage Bed', 
    price: 59999, 
    rating: 4.7, 
    reviews: 95, 
    imageId: 'product-bed-3', 
    href: '/product/smart-storage-bed', 
    category: 'Beds', 
    material: 'Solid Wood', 
    size: 'Queen',
    description: 'Maximize your space with the Smart Storage Bed. Featuring four spacious drawers integrated into the base, this bed combines modern style with practical functionality, perfect for contemporary living.',
    features: [
      'Four large under-bed storage drawers',
      'Hydraulic lift for easy access (optional)',
      'Sleek, minimalist design',
      'Durable engineered wood construction',
    ],
  },
  { 
    id: '8', 
    slug: 'minimalist-platform-bed',
    name: 'Minimalist Platform Bed', 
    price: 38999, 
    rating: 4.8, 
    reviews: 65, 
    imageId: 'product-bed-4', 
    href: '/product/minimalist-platform-bed', 
    category: 'Beds', 
    material: 'Metal', 
    size: 'Double',
    description: 'Clean lines and a low profile define the Minimalist Platform Bed. Its simple yet sturdy metal frame provides a modern, industrial look that complements any decor style without overwhelming the space.',
    features: [
      'Sleek, low-profile design',
      'Robust and silent metal frame',
      'Ample under-bed clearance',
      'No box spring required',
    ],
  },
  // Sofas
  { 
    id: '9', 
    slug: 'modern-l-shape-sofa',
    name: 'Modern L-Shape Sofa', 
    price: 79999, 
    rating: 4.9, 
    reviews: 150, 
    imageId: 'product-sofa-1', 
    href: '/product/modern-l-shape-sofa', 
    category: 'Sofas', 
    material: 'Fabric', 
    size: 'L-Shape',
    description: 'The Modern L-Shape Sofa is the ultimate family centerpiece. Its generous size, comfortable chaise lounge, and clean design provide ample seating and a touch of contemporary style for your living room.',
    features: [
      'Spacious L-shape design with chaise',
      'High-resilience foam for lasting comfort',
      'Durable and soft fabric upholstery',
      'Modular design for flexible arrangement',
    ],
  },
  { 
    id: '10', 
    slug: 'classic-3-seater-sofa',
    name: 'Classic 3-Seater Sofa', 
    price: 65000, 
    oldPrice: 72000, 
    rating: 4.8, 
    reviews: 200, 
    imageId: 'product-sofa-2', 
    href: '/product/classic-3-seater-sofa', 
    category: 'Sofas', 
    material: 'Leatherette', 
    size: '3-Seater',
    description: 'Elegance and durability come together in the Classic 3-Seater Sofa. Upholstered in premium leatherette with plush cushioning, it offers timeless style and a comfortable spot for relaxation.',
    features: [
      'Timeless design with rolled arms',
      'Premium, easy-to-clean leatherette',
      'Solid wood frame for enhanced durability',
      'Comfortably seats three adults',
    ],
  },
  { 
    id: '11', 
    slug: 'cozy-2-seater-loveseat',
    name: 'Cozy 2-Seater Loveseat', 
    price: 48000, 
    rating: 4.7, 
    reviews: 120, 
    imageId: 'product-sofa-3', 
    href: '/product/cozy-2-seater-loveseat', 
    category: 'Sofas', 
    material: 'Velvet', 
    size: '2-Seater',
    description: 'Perfect for smaller spaces, the Cozy 2-Seater Loveseat adds a touch of glamour and comfort. Its soft velvet upholstery and compact design make it an ideal addition to any room.',
    features: [
      'Luxurious and soft velvet fabric',
      'Compact design perfect for apartments',
      'Tapered wooden legs for a mid-century look',
      'Deep, comfortable seating',
    ],
  },
  { 
    id: '12', 
    slug: 'convertible-sofa-bed',
    name: 'Convertible Sofa Bed', 
    price: 55000, 
    rating: 4.6, 
    reviews: 90, 
    imageId: 'product-sofa-4', 
    href: '/product/convertible-sofa-bed', 
    category: 'Sofas', 
    material: 'Fabric', 
    size: 'Sofa Bed',
    description: 'Functionality meets style in the Convertible Sofa Bed. Easily transform it from a comfortable sofa to a convenient guest bed in seconds, making it a versatile solution for modern homes.',
    features: [
      'Easily converts from sofa to bed',
      'Click-clack mechanism',
      'Sturdy frame and durable fabric',
      'Includes two matching bolster pillows',
    ],
  },
];
